markdown: pandoc
pandoc:
pandoc:
  skip: false
  bundle_permalink: ':output_ext/:slug.:output_ext'
  papersize: 'a5paper'
  sheetsize: 'a4paper'
  imposition: true
  binder: true
  flags: '--csl=../apa.csl --bibliography=../ref.bib --smart -V lang=spanish
          --section-divs --email-obfuscation=references'
  site_flags: '--toc --template=layouts/toc.html'
  outputs:
    pdf: '-V fontsize=10pt,a5paper,twoside
          -V documentclass=book
          -V geometry=hcentering
          -V geometry=bindingoffset=1cm
          --latex-engine=xelatex
          --table-of-contents
          --include-in-header=layouts/header.tex
          --include-before-body=layouts/license.tex'
    epub: '-V lang=es --epub-chapter-level=2'
    mediawiki:
    rst:
    latex: '-V fontsize=10pt,a5paper,twoside
            -V documentclass=book
            -V geometry=hcentering
            -V geometry=bindingoffset=1cm
            --latex-engine=xelatex
            --table-of-contents
            --include-in-header=layouts/header.tex
            --include-before-body=layouts/license.tex'

destination: /srv/http/endefensadelsl.org
source:   ./src
layouts:  ./layouts
plugins:  ./_plugins

exclude: [ tmp, layouts ]

permalink: ":title.html"

lsi: false

torrent:
  file: endefensadel.torrent
