---
sass:
  load_paths:
    - node_modules
  style: compressed
  quiet_deps: true
  silence_deprecations:
    - import
commit_url: "https://0xacab.org/edsl/articulos/-/commit/:oid"
plugins:
- jekyll-relative-urls
- jekyll-printing-press
- sutty-liquid
markdown: Pandoc
permalink: ":title.html"
url: "https://endefensadelsl.org"
title: En Defensa del Software Libre
pandoc:
  documents:
  - posts
  - categories
# printing:
#   sheetsize: a4paper
#   signature: false
#   formats:
#   - imposition
#   - binder
  options:
    common:
      citeproc: true
      from: markdown+smart
      csl: apa.csl
      bibliography: ref.bib
      section-divs: true
      email-obfuscation: references
      variable:
        lang: es
    html5:
      toc: true
      template: _layouts/toc.html
    mediawiki: true
    rst: true
    pdf: &pdf
      pdf-engine: tectonic
      standalone: true
      table-of-contents: true
      variable:
        papersize: a5
        fontsize: 10pt
        documentclass: book
        geometry:
        - hcentering
        - bindingoffset=1cm
        - bmargin=2.5cm
        links-as-notes: true
      include-in-header: _layouts/header.tex
      include-before-body: _layouts/license.tex
    epub:
      split-level: 2
    latex:
      <<: *pdf
